version: 2

registries:
  dhi-io:
    type: docker-registry
    url: https://dhi.io
    username: ${{secrets.DHI_USERNAME}}
    password: ${{secrets.DHI_PASSWORD}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    groups:
      pre-commit:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directories:
      - "/api"
      - "/web"
    registries:
      - dhi-io
    groups:
      dockerfile:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/api"
    groups:
      api:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/docs"
    groups:
      docs:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/web"
    groups:
      web:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "@hey-api/openapi-ts"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    cooldown:
      default-days: 7
