version: 2
registries:
  dhi-io:
    type: docker-registry
    url: https://dhi.io
    username: ${{secrets.DHI_USERNAME}}
    password: ${{secrets.DHI_PASSWORD}}
updates:
  - package-ecosystem: "npm"
    directories:
      - "/web"
      - "/documentation"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      web:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      api:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/web"
      - "/api"
    registries:
      - dhi-io
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      dockerfile:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
