version: 2
registries:
  dhi-io:
    type: docker-registry
    url: https://dhi.io
    username: ${{secrets.DHI_USERNAME}}
    password: ${{secrets.DHI_PASSWORD}}
updates:
  - package-ecosystem: "npm"
    directories:
      - "/web"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      web:
        exclude-patterns:
          - "@hey-api/openapi-ts"
        update-types:
          - "minor"
          - "patch"
      openapi-ts:
        patterns:
          - "@hey-api/openapi-ts"

  - package-ecosystem: "docker"
    directories:
      - "/web"
      - "/api"
    registries:
      - dhi-io
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      dockerfile:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directories:
      - "/docs"
      - "/api"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      docs:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
