version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      web:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      api:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/web"
      - "/api"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
    groups:
      dockerfile:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # when template is used, recommended interval is "weekly"
