version: "3.8"

services:
  api:
    image: development
    build:
      target: development
    environment:
      ENVIRONMENT: local
      MONGODB_DATABASE: db
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongodb
      MONGODB_HOSTNAME: db
      MONGODB_PORT: 27017
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs=
      AUTH_ENABLED: "False"
    depends_on:
      - db
    links:
      - db

  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: db


