services:
  api:
    build:
      target: development
    image: template-api-dev
    environment:
      ENVIRONMENT: local
      LOGGING_LEVEL: debug
    develop:
      watch:
        - action: sync+restart
          path: ./api/src
          target: /app/src
          ignore:
            - .venv/
        - action: rebuild
          path: ./api/uv.lock
        - action: restart
          path: ./.env

  nginx:
    build:
      target: nginx-dev

  web:
    restart: unless-stopped
    build:
      target: development
      context: ./web
    image: template-web-dev
    stdin_open: true
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /code/src
        - action: rebuild
          path: ./web/yarn.lock

  db:
    volumes:
      - database:/data/db

  oauth2:
    environment:
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true"
    volumes:
      - ./web/oauth2/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./web/oauth2/oauth2-proxy.toml:/etc/oauth2-proxy.toml
      - ./web/oauth2/oauth2-proxy.yaml:/etc/oauth2-proxy.yaml

volumes:
  database:
