version: "3.8"

services:
  nginx:
    restart: unless-stopped
    build: ./nginx
    image: boilerplate.azurecr.io/nginx:latest
    ports:
      - "80:8080"
    links:
      - web
      - api

  api:
    build: ./api
    image: ghcr.io/equinor/template-fastapi-react/api
    restart: unless-stopped
    depends_on:
      - db

  web:
    build: ./web
    image: ghcr.io/equinor/template-fastapi-react/web
    restart: unless-stopped

  db:
    image: mongo:5.0.9
    restart: unless-stopped
    command: --auth --quiet
