// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTodo, deleteTodoById, getAllTodos, getHealthCheckGet, getTodoById, type Options, track, updateTodoById, whoami } from '../sdk.gen';
import type { CreateTodoData, CreateTodoError, CreateTodoResponse, DeleteTodoByIdData, DeleteTodoByIdError, DeleteTodoByIdResponse2, GetAllTodosData, GetAllTodosError, GetAllTodosResponse, GetHealthCheckGetData, GetHealthCheckGetError, GetHealthCheckGetResponse, GetTodoByIdData, GetTodoByIdError, GetTodoByIdResponse2, TrackData, TrackError, TrackResponse, UpdateTodoByIdData, UpdateTodoByIdError, UpdateTodoByIdResponse, WhoamiData, WhoamiError, WhoamiResponse } from '../types.gen';

/**
 * Track
 */
export const trackMutation = (options?: Partial<Options<TrackData>>): UseMutationOptions<TrackResponse, TrackError, Options<TrackData>> => {
    const mutationOptions: UseMutationOptions<TrackResponse, TrackError, Options<TrackData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await track({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllTodosQueryKey = (options?: Options<GetAllTodosData>) => createQueryKey('getAllTodos', options);

/**
 * Get Todo All
 */
export const getAllTodosOptions = (options?: Options<GetAllTodosData>) => queryOptions<GetAllTodosResponse, GetAllTodosError, GetAllTodosResponse, ReturnType<typeof getAllTodosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllTodos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllTodosQueryKey(options)
});

/**
 * Add Todo
 */
export const createTodoMutation = (options?: Partial<Options<CreateTodoData>>): UseMutationOptions<CreateTodoResponse, CreateTodoError, Options<CreateTodoData>> => {
    const mutationOptions: UseMutationOptions<CreateTodoResponse, CreateTodoError, Options<CreateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Todo By Id
 */
export const deleteTodoByIdMutation = (options?: Partial<Options<DeleteTodoByIdData>>): UseMutationOptions<DeleteTodoByIdResponse2, DeleteTodoByIdError, Options<DeleteTodoByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteTodoByIdResponse2, DeleteTodoByIdError, Options<DeleteTodoByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTodoById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTodoByIdQueryKey = (options: Options<GetTodoByIdData>) => createQueryKey('getTodoById', options);

/**
 * Get Todo By Id
 */
export const getTodoByIdOptions = (options: Options<GetTodoByIdData>) => queryOptions<GetTodoByIdResponse2, GetTodoByIdError, GetTodoByIdResponse2, ReturnType<typeof getTodoByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTodoById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTodoByIdQueryKey(options)
});

/**
 * Update Todo
 */
export const updateTodoByIdMutation = (options?: Partial<Options<UpdateTodoByIdData>>): UseMutationOptions<UpdateTodoByIdResponse, UpdateTodoByIdError, Options<UpdateTodoByIdData>> => {
    const mutationOptions: UseMutationOptions<UpdateTodoByIdResponse, UpdateTodoByIdError, Options<UpdateTodoByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTodoById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const whoamiQueryKey = (options?: Options<WhoamiData>) => createQueryKey('whoami', options);

/**
 * Get Information On Authenticated User
 */
export const whoamiOptions = (options?: Options<WhoamiData>) => queryOptions<WhoamiResponse, WhoamiError, WhoamiResponse, ReturnType<typeof whoamiQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await whoami({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: whoamiQueryKey(options)
});

export const getHealthCheckGetQueryKey = (options?: Options<GetHealthCheckGetData>) => createQueryKey('getHealthCheckGet', options);

/**
 * Get
 */
export const getHealthCheckGetOptions = (options?: Options<GetHealthCheckGetData>) => queryOptions<GetHealthCheckGetResponse, GetHealthCheckGetError, GetHealthCheckGetResponse, ReturnType<typeof getHealthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthCheckGetQueryKey(options)
});
