["generate:openapi-spec"]
description = "Generate the OpenAPI JSON Schema for the API"
depends = ["install-dependencies:api"]
dir = "{{config_root}}/api"
run = "uv run python -m app open-api"

["generate:api-client-from-spec"]
description = "Generate typescript types from the OpenAPI JSON Schema"
depends = ["generate:openapi-spec"]
dir = "{{config_root}}/web"
run = "yarn install && yarn generate"
