["lint:api:typecheck"]
description = "Typecheck the API, with mypy"
dir = "{{config_root}}/api"
run = "uv run mypy src"

["lint:api"]
description = "Lint the API"
run = [
    "mise run lint:api:typecheck",
]

["lint:web:typecheck"]
description = "Typecheck the Web application, by compiling the TypeScript code"
depends = ["install-dependencies:web"]
dir = "{{config_root}}/web"
run = "yarn compile"

["lint:web:query"]
description = "Lint TanStack Query usage in the Web application"
depends = ["install-dependencies:web"]
dir = "{{config_root}}/web"
run = "yarn lint:query"

["lint:web"]
description = "Lint the Web application"
run = [
    "mise run lint:web:typecheck",
    "mise run lint:web:query",
]

["lint:shell"]
description = "Lint shell scripts with shellcheck"
dir = "{{config_root}}"
run = "shellcheck --external-sources IaC/*.sh .mise/tasks/iac/* redis/rootfs/usr/local/sbin/*.sh web/oauth2/*.sh api/src/*.sh"

[lint]
description = "Lint the entire project"
depends = ["lint:shell", "lint:api", "lint:web"]
run = "mise fmt"
