// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AccessLevel
 */
export const zAccessLevel = z.union([
    z.literal(2),
    z.literal(1),
    z.literal(0)
]);

/**
 * AddTodoRequest
 */
export const zAddTodoRequest = z.object({
    title: z.string().min(1).max(300)
});

/**
 * AddTodoResponse
 */
export const zAddTodoResponse = z.object({
    id: z.string(),
    user_id: z.string(),
    title: z.string(),
    is_completed: z.boolean().optional().default(false)
});

/**
 * DeleteTodoByIdResponse
 */
export const zDeleteTodoByIdResponse = z.object({
    success: z.boolean()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    status: z.int().optional().default(500),
    type: z.string().optional().default('ApplicationException'),
    message: z.string().optional().default('The requested operation failed'),
    debug: z.string().optional().default('An unknown and unhandled exception occurred in the API'),
    extra: z.record(z.string(), z.unknown()).nullish()
});

/**
 * EventData
 */
export const zEventData = z.object({
    ver: z.int(),
    properties: z.record(z.string(), z.unknown()),
    name: z.string(),
    url: z.string().optional(),
    measurements: z.record(z.string(), z.number()).optional()
});

/**
 * ExceptionData
 */
export const zExceptionData = z.object({
    ver: z.int(),
    exceptions: z.array(z.record(z.string(), z.unknown())),
    properties: z.record(z.string(), z.unknown())
});

/**
 * GetTodoAllResponse
 */
export const zGetTodoAllResponse = z.object({
    id: z.string(),
    user_id: z.string(),
    title: z.string(),
    is_completed: z.boolean()
});

/**
 * GetTodoByIdResponse
 */
export const zGetTodoByIdResponse = z.object({
    id: z.string(),
    user_id: z.string(),
    title: z.string(),
    is_completed: z.boolean().optional().default(false)
});

/**
 * MetricsData
 */
export const zMetricsData = z.object({
    ver: z.int(),
    metrics: z.array(z.record(z.string(), z.unknown())),
    properties: z.record(z.string(), z.unknown())
});

/**
 * EventBase
 */
export const zEventBase = z.object({
    baseType: z.string(),
    baseData: z.union([
        zEventData,
        zMetricsData,
        zExceptionData
    ])
});

/**
 * Event
 */
export const zEvent = z.object({
    name: z.string(),
    tags: z.record(z.string(), z.string()),
    time: z.iso.datetime(),
    data: zEventBase
});

/**
 * TelemetryErrorDetails
 */
export const zTelemetryErrorDetails = z.object({
    index: z.int(),
    statusCode: z.int(),
    message: z.string()
});

/**
 * TelemetryResult
 */
export const zTelemetryResult = z.object({
    items_received: z.int(),
    items_accepted: z.int(),
    errors: z.array(zTelemetryErrorDetails)
});

/**
 * UpdateTodoRequest
 */
export const zUpdateTodoRequest = z.object({
    title: z.string().min(1).max(300).optional().default(''),
    is_completed: z.boolean()
});

/**
 * UpdateTodoResponse
 */
export const zUpdateTodoResponse = z.object({
    success: z.boolean()
});

/**
 * User
 */
export const zUser = z.object({
    user_id: z.string(),
    email: z.string().nullish(),
    full_name: z.string().nullish(),
    roles: z.array(z.string()).optional().default([]),
    scope: zAccessLevel.optional().default(2)
});

/**
 * Events
 */
export const zTrackBody = z.array(zEvent);

/**
 * Response Track
 *
 * Successful Response
 */
export const zTrackResponse = zTelemetryResult.nullable();

/**
 * Response Getalltodos
 *
 * Successful Response
 */
export const zGetAllTodosResponse = z.array(zGetTodoAllResponse);

export const zCreateTodoBody = zAddTodoRequest;

/**
 * Successful Response
 */
export const zCreateTodoResponse = zAddTodoResponse;

export const zDeleteTodoByIdPath = z.object({
    id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteTodoByIdResponse2 = zDeleteTodoByIdResponse;

export const zGetTodoByIdPath = z.object({
    id: z.string()
});

/**
 * Successful Response
 */
export const zGetTodoByIdResponse2 = zGetTodoByIdResponse;

export const zUpdateTodoByIdBody = zUpdateTodoRequest;

export const zUpdateTodoByIdPath = z.object({
    id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateTodoByIdResponse = zUpdateTodoResponse;

/**
 * Successful Response
 */
export const zWhoamiResponse = zUser;

/**
 * Response 200 Get Health Check Get
 *
 * Successful Response
 */
export const zGetHealthCheckGetResponse = z.string();
