auth_request                                /oauth2/auth;

# pass the id_token (Authorization) and access_token to the upstream
auth_request_set $token                     $upstream_http_authorization;
proxy_set_header Authorization              $token;

auth_request_set $access_token              $upstream_http_x_auth_request_access_token;
proxy_set_header X-Forwarded-Access-Token   $access_token;
