[tools]
python = "3.14.4"
node = { version = "24.14.1", postinstall = "mise tasks run tools:yarn" }
pre-commit = "4.5.1"
uv = "0.11.6"

[task_config]
includes = [".mise/tasks/*.toml"]

[settings]
experimental = true
python.uv_venv_auto = true
