[tools]
python = "3.14.3"
node = { version = "24.13.1", postinstall = "mise tasks run tools:yarn" }
pre-commit = "4.5.1"
uv = "0.10.8"

[task_config]
includes = [".mise/tasks/*.toml"]

[settings]
experimental = true
python.uv_venv_auto = true
