[tools]
python = "3.14.3"
node = { version = "24.13.1", postinstall = "mise tasks run tools:yarn" }
pre-commit = "4.5.1"
uv = "0.10.8"

[tasks."tools:yarn"]
hide = true
dir = "{{config_root}}/web"
run = ["corepack enable", "corepack install"]

[tasks."typecheck:api"]
dir = "{{config_root}}/api"
run = "uv run mypy src"

[tasks."typecheck:web"]
depends = ["dependencies:web"]
dir = "{{config_root}}/web"
run = "yarn compile"

[tasks."dependencies:api"]
dir = "{{config_root}}/api"
run = "uv sync"

[tasks."dependencies:web"]
dir = "{{config_root}}/web"
run = "yarn install"

[tasks.generate-openapi-spec]
depends = ["dependencies:api"]
dir = "{{config_root}}/api"
run = "uv run python -m app open-api"

[tasks.generate-api-client-from-spec]
dir = "{{config_root}}/web"
run = "openapi -i ../api/.openapi.json -o './src/api/generated'"

[settings]
experimental = true
python.uv_venv_auto = true
