@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(application_users, "Application User", "A user of the todo application.")
System(web_application, "Single-Page Application", "Provide all the todo functionality to users via their web browser. ")
System(rest_api, "REST API", "Provides todo functionality via a JSON/HTTPS API.")
Rel(application_users, web_application, "Uses")
Rel(web_application, rest_api, "Makes API calls to", "JSON/HTTPS")
ContainerDb(database, "Database", "MongoDB", "Store todos")
Rel(rest_api, database, "Read and write to", "JDBC")

@enduml