@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(application_users, "Application User", "A user of the todo application.")
System(application, "Todo Application", "Provides todo functionality")
System_Ext(azure_active_directory, "Oauth2 Authorization Server", "Provides authentication and provides userid and roles for access control")
Rel(application_users, application, "Uses")
Rel(application, azure_active_directory, "Uses")

@enduml