name: "Test"
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:
    secrets:
      CR_SECRET:
        description: "Secret to authenticate if using an other container registry than Github"
        required: false

env:
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: $GITHUB_ACTOR
  API_IMAGE: ghcr.io/equinor/template-fastapi-react/api
  WEB_IMAGE: ghcr.io/equinor/template-fastapi-react/web

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: "pre-commit"
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@v6

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@v3
        timeout-minutes: 5

      - name: "Run: pre-commit"
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  mypy:
    runs-on: ubuntu-latest
    name: "mypy static type checking"
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@v6

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@v3
        timeout-minutes: 5

      - name: "Setup: install uv"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: "Setup: install dependencies"
        run: mise run dependencies:api

      - name: "Run: mypy"
        run: mise run typecheck:api

  typescript-compile:
    runs-on: ubuntu-latest
    name: "typescript compilation"
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: "Setup: check out repository"
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            web

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: /home/runner/.yarn/berry/cache

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@v3
        timeout-minutes: 5

      - name: "Run: compile"
        run: mise run typecheck:web

  validate-radix-config:
    runs-on: ubuntu-latest
    name: "validate Radix config"
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@v6
      - uses: equinor/radix-github-actions@v2
      - name: "Run: validate radix config"
        run: rx validate radix-config
