name: "Test"
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:
    secrets:
      CR_SECRET:
        description: "Secret to authenticate if using an other container registry than Github"
        required: false

env:
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: $GITHUB_ACTOR
  API_IMAGE: ghcr.io/equinor/template-fastapi-react/api
  WEB_IMAGE: ghcr.io/equinor/template-fastapi-react/web

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: "pre-commit"
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        timeout-minutes: 5

      - name: "Run: pre-commit"
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --all-files

  mypy:
    runs-on: ubuntu-latest
    name: "mypy static type checking"
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        timeout-minutes: 5

      - name: "Setup: install uv"
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: "Setup: install dependencies"
        run: mise run install-dependencies:api

      - name: "Run: mypy"
        run: mise run lint:api:typecheck

  typescript-compile:
    runs-on: ubuntu-latest
    name: "typescript compilation"
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: "Setup: check out repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github
            .mise
            web

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: /home/runner/.yarn/berry/cache

      - name: "Setup: Runtimes"
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        timeout-minutes: 5

      - name: "Run: compile"
        run: mise run lint:web:typecheck

  validate-radix-config:
    runs-on: ubuntu-latest
    name: "validate Radix config"
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: equinor/radix-github-actions@b23674a56b82a1da783b507bc7f15e7ca7067dd8 # v2.0.2
      - name: "Run: validate radix config"
        run: rx validate radix-config
