name: "On PR updated"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linting-and-checks:
    name: "Linting and checks"
    uses: ./.github/workflows/linting-and-checks.yaml

  tests:
    name: "Tests"
    uses: ./.github/workflows/tests.yaml
