name: "On PR updated"
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  linting-and-checks:
    name: "Linting and checks"
    uses: ./.github/workflows/linting-and-checks.yaml

  tests:
    name: "Tests"
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/tests.yaml
