name: "Releases"

# This action works when creating a release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  publish-production:
    needs: tests
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: production
      oauth-redirect-url: 'https://template-fastapi-react.app.radix.equinor.com'

  deploy-prod:
    needs: publish-production
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}