name: Generate documentation

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write # actions/deploy-pages uses OIDC

# Force previous deployment to complete before starting a new one
# to prevent deployments overwriting each other
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish-docs:
    name: "Publish docs site"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            .github
            .mise
            docs

      - name: "Setup: Environment"
        uses: ./.github/actions/setup-environment
        timeout-minutes: 5

      - name: Build website
        working-directory: ./docs
        run: uv run zensical build

      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
