name: Generate documentation

on:
  workflow_dispatch:
  workflow_call:

env:
  GITHUB_PAGES_BRANCH: gh-pages

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: documentation/yarn.lock

      - name: Install dependencies
        working-directory: documentation
        run: yarn install --frozen-lockfile

      - name: Build documentation
        working-directory: documentation
        run: yarn build

      - name: Push static files to Github Pages branch
        run: |
          cd documentation/build
          CREATED_FROM_REF=$(git rev-parse --short HEAD)
          git init
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $GITHUB_PAGES_BRANCH
          git remote add $GITHUB_PAGES_BRANCH https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/equinor/template-fastapi-react
          git add .
          git commit -m "Built from commit '$CREATED_FROM_REF'"
          git push -f --set-upstream gh-pages gh-pages
