name: "Publish container images"
on:
  workflow_dispatch:
  workflow_call: # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tags:
        description: "Which tag to give the images. Supports multiple tags if comma separated, ie 'tag1,tag2'"
        required: true
        type: string
    secrets:
      CR_SECRET:
        description: "Secret to authenticate if using an other container registry than Github"
        required: false

permissions:
  contents: read
  packages: write

env:
  API_IMAGE: ghcr.io/equinor/template-fastapi-react/api
  NGINX_IMAGE: ghcr.io/equinor/template-fastapi-react/nginx

jobs:
  build-and-publish-nginx-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: "Login to image registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup: Buildx"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: "Prepare: version.txt and tags"
        id: prep
        run: |
          printf "$(git log -n 1 --format=format:'hash: %h%ndate: %cs%nrefs: %d' --decorate=short --decorate-refs=refs/tags | sed 's/ (tag: \([^\s]*\))/\1/')" > ./web/public/version.txt
          {
            echo "tags<<EOF"
            IFS=','
            for t in ${{ inputs.image-tags }}; do
              echo "${NGINX_IMAGE}:${t}"
            done
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: "Build & publish web"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ./web
          target: nginx-prod
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=registry,ref=${{ env.NGINX_IMAGE }}:latest
          cache-to: type=inline
          build-args: |
            AUTH_ENABLED=1
            AUTH_SCOPE=api://${{ vars.AZURE_CLIENT_ID }}/api
            CLIENT_ID=${{ vars.AZURE_CLIENT_ID }}
            TENANT_ID=${{ vars.AZURE_TENANT_ID }}

  build-and-publish-api-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: "Login to image registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup: Buildx"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: "Prepare: version.txt and tags"
        id: prep
        run: |
          printf "$(git log -n 1 --format=format:'hash: %h%ndate: %cs%nrefs: %d' --decorate=short --decorate-refs=refs/tags | sed 's/ (tag: \([^\s]*\))/\1/')" > ./api/src/version.txt
          {
            echo "tags<<EOF"
            IFS=','
            for t in ${{ inputs.image-tags }}; do
              echo "${API_IMAGE}:${t}"
            done
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: "Build & publish API"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ./api
          target: prod
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=registry,ref=${{ env.API_IMAGE }}:latest
          cache-to: type=inline
