name: Generate documentation

on:
  workflow_dispatch:
  workflow_call:

env:
  GITHUB_PAGES_BRANCH: gh-pages

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies and build website
        run: |
          cd docs
          uv sync --locked
          uv run zensical build

      - name: Push static files to Github Pages branch
        run: |
          cd docs/site
          CREATED_FROM_REF=$(git rev-parse --short HEAD)
          git init
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $GITHUB_PAGES_BRANCH
          git remote add $GITHUB_PAGES_BRANCH https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/equinor/template-fastapi-react
          git add .
          git commit -m "Built from commit '$CREATED_FROM_REF'"
          git push -f --set-upstream gh-pages gh-pages
