name: release-to-production

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  publish-production:
    needs: tests
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: production
      oauth-redirect-url: 'https://template-fastapi-react.app.radix.equinor.com'

  deploy-prod:
    needs: publish-production
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}