name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: release-please-action
          extra-files: |
            api/pyproject.toml
            api/src/app.py
    outputs:
       release_created: ${{ steps.release.outputs.release_created }}

  deploy-prod:
    needs: release-please
    uses: ./.github/workflows/release-production.yaml
    if: ${{ needs.release-please.outputs.release_created }}
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}