name: release-to-production

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  publish-production:
    needs: tests
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: production
      oauth-redirect-url: 'https://template-fastapi-react.app.playground.radix.equinor.com'

  deploy-prod:
    needs: publish-production
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'