name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: "If 'true', a release PR was merged and GitHub release was created"
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        description: "The released tag. Ex 'v1.2.3'"
        value: ${{ jobs.release-please.outputs.tag_name }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: release-please
        id: release-please
        uses: googleapis/release-please-action@v5
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ steps.generate-token.outputs.token }}
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
