name: "Rollback prod to an older release"
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "GitHub release tag. Must match a Docker image tag"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  set-prod-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          [
            ghcr.io/equinor/template-fastapi-react/api,
            ghcr.io/equinor/template-fastapi-react/web,
            ghcr.io/equinor/template-fastapi-react/nginx,
          ]
    steps:
      - name: "Login to image registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set prod tag on older image"
        run: |
          echo "Tagging ${{ matrix.image }}:${{ inputs.release-tag }} with 'production'"
          docker pull ${{ matrix.image }}:${{ inputs.release-tag }}
          docker tag ${{ matrix.image }}:${{ inputs.release-tag }} ${{ matrix.image }}:production
          docker push ${{ matrix.image }}:production

  # uncomment to apply rollback to radix
  # deploy:
  #   needs: set-prod-tag
  #   uses: ./.github/workflows/deploy-to-radix.yaml
  #   with:
  #     radix-environment: "prod"
