name: "Test"
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github
            .mise
            api

      - name: "Setup: Environment"
        uses: ./.github/actions/setup-environment
        timeout-minutes: 5

      - name: "Run: pytest unit tests"
        run: mise run test:api:unit

  api-integration-tests:
    runs-on: ubuntu-latest
    env:
      API_IMAGE: ghcr.io/equinor/template-fastapi-react/api
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to image registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          docker pull $API_IMAGE
          docker build --target development --tag api-development ./api # TODO: --cache-from $API_IMAGE
      - name: BDD Integration tests
        if: ${{ false }} # disable for now
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run api behave

      - name: Pytest Integration tests
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm api pytest --integration

  web-tests:
    runs-on: ubuntu-latest
    if: ${{ false }} # disable for now as they do not currently work
    env:
      NGINX_IMAGE: ghcr.io/equinor/template-fastapi-react/nginx
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to image registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Web Image
        run: |
          docker pull $NGINX_IMAGE
          docker build --cache-from $NGINX_IMAGE --target development --tag web-dev ./web

      - name: Run Web tests
        if: ${{ false }} # disable for now as they do not currently work
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm web yarn test

  docs-tests:
    name: test-docs
    runs-on: ubuntu-latest

    steps:
      - name: "Setup: checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github
            .mise
            docs

      - name: "Setup: Environment"
        uses: ./.github/actions/setup-environment
        timeout-minutes: 5

      - name: "Run: build docs site"
        run: mise run docs:build
