enableScripts: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.4.1.cjs
