nodeLinker: node-modules

enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "@equinor/eds-utils@0.7.0":
    peerDependencies:
      "@babel/core": "*"
  "@equinor/eds-core-react@0.29.1":
    peerDependencies:
      "@babel/core": "*"
