nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "@equinor/eds-utils@0.7.0":
    peerDependencies:
      "@babel/core": "*"
  "@equinor/eds-core-react@0.29.1":
    peerDependencies:
      "@babel/core": "*"
  "eslint-config-react-app@7.0.1":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "react-scripts@5.0.1":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"